version: '3'
services:
  web:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: biblioteca-game
    volumes:
      - .:/var/www/
    ports:
      - "8010:80"
    tty: true
      #command: /bin/bash -c "apt-get update && apt-get install -y apache2 && apache2"

networks: 
  net01:
    driver: bridge
